# Generated by Django 6.0.2 on 2026-02-10 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('required_skills', models.TextField(help_text='JSON list of required skills')),
            ],
        ),
        migrations.CreateModel(
            name='LearningResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100)),
                ('resource_name', models.CharField(max_length=200)),
                ('link', models.URLField(max_length=500)),
                ('resource_type', models.CharField(choices=[('Course', 'Course'), ('Documentation', 'Documentation'), ('Tutorial', 'Tutorial'), ('Certification', 'Certification'), ('Tool', 'Tool'), ('Practice', 'Practice'), ('Search', 'Search')], max_length=50)),
            ],
        ),
    ]
