# Generated by Django 6.0.2 on 2026-02-11 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firebase_uid', models.CharField(max_length=128)),
                ('role', models.CharField(max_length=200)),
                ('match_percentage', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('skills_count', models.IntegerField()),
                ('missing_skills', models.TextField(help_text='JSON list of missing skills')),
            ],
        ),
    ]
